name: 'Terraform Plan'

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  terraform_plan:
    name: 'Plan'
    runs-on: ubuntu-latest
    env:
      TF_VAR_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }} >> $GITHUB_ENV
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.7'

      - name: Terraform Init
        run: terraform init


      - name: Terraform Plan
        run: | 
          terraform plan -input=false
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: path/to/terraform.plan
