name: 'Terraform Plan'

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  terraform_plan:
    name: 'Plan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.8.2'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Terraform Init
        run: terraform init
        working-directory: fouad

      - name: Terraform Plan
        run: terraform plan -var="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"
        working-directory: fouad

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: path/to/terraform.plan
