name: 'Terraform Plan'

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  terraform_plan:
    name: 'Plan'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.5.7'

      - name: Configure azure credentials
        run: |
          terraform init
          terraform plan
        env:
          ARM_sp_client_id: ${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          ARM_sp_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
          ARM_tenant_id: ${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
          ARM_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: path/to/terraform.plan
